#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
- name: Check if vrops already exists
  does_vm_exist:
    vcenter_host: "{{ vcenter_host }}"
    vcenter_user: "{{ vcenter_user }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_port: "{{ vcenter_port }}"
    vm_name: "{{ vrops_name }}"
  register: vrops_appliance_exists
  tags:
    - vropsova_deploy

- name: Deploy vRealize Operations OVA
  shell: >
    {{ vrops_ovftool }}
    '--name={{ vrops_name }}'
    --acceptAllEulas
    --allowExtraConfig
    --X:enableHiddenProperties
    --noSSLVerify
    --datastore={{ vrops_datastore }}
    --diskMode={{ vrops_disk_mode }}
    --ipProtocol={{ vrops_ip_protocol }}
    --deploymentOption={{ vrops_deployment_option }}
    '--network={{ vrops_network }}'
    '--prop:vami.gateway.vRealize_Operations_Manager_Appliance={{ vrops_gateway }}'
    '--prop:vami.DNS.vRealize_Operations_Manager_Appliance={{ vrops_dns }}'
    '--prop:vami.ip0.vRealize_Operations_Manager_Appliance={{ vrops_ip }}'
    '--prop:vami.netmask0.vRealize_Operations_Manager_Appliance={{ vrops_netmask }}'
    '--prop:guestinfo.cis.appliance.ssh.enabled={{ vrops_enable_ssh | string }}'
    --powerOn={{ vrops_poweron | string }}
    '{{ vrops_ova_location }}/{{ vrops_ova }}'
    'vi://{{ vcenter_user | urlencode }}:{{ vcenter_password | urlencode }}@{{ vcenter_host }}/{{ datacenter_name }}/host/{{ vrops_cluster }}/'
  when: vrops_appliance_exists.msg == 'Appliance does not exist.'
  tags:
    - vropsova_deploy
